Add a link to a Python implementation of the standard
keith-turner/ecoji pull request #21
Opened 2018-04-10 18:30 UTC by mecforlove

Hello, thanks for your awesome encoding idea. I went through your code and wrote the Python version.

2018-04-24 10:17 UTC, mecforlove commented
@keith-turner Please deal with this pr. Thanks.

2018-04-26 13:18 UTC, keith-turner commented
@mecforlove sorry for the delay.   I want to look at your project before adding the link and have not had the time.  I will do this shortly.

2018-04-26 13:35 UTC, Rayne requested changes

2018-04-26 13:35 UTC, Rayne commented on README.md
> +| [Python](https://github.com/mecforlove/ecoji) | Implementation of Ecoji written in the Python3 programming language.
That's the wrong link. It should be https://github.com/mecforlove/ecoji-py instead.

2018-04-26 13:58 UTC, mecforlove commented
@Rayne sorry, I fixed it.

2018-04-26 14:18 UTC, Rayne approved these changes

2018-04-27 02:20 UTC, keith-turner commented
@mecforlove I spent a while testing your implementation and it works great!   I need to write an automated test suite so I Can more quickly test different implementation.  Again, sorry for the delay.  Your implementation is very nice!

2018-04-27 02:20 UTC, merged